log: '/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/results/xy'

train_data:
  type: "multi"
  path_data: [
    #'/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_1particle_training.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_3particle_training.nc',
    #'/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_multiparticle_training.nc',
    #'/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_12-25particle_gamma_600x400_training.nc'
    ]
  output_cols: ["x", "y", "z", "d"]
  maxnum_particles: 3
  shuffle: True
  labels: True
  null_weight: 0.0
  bins: 10
  
validation_data:
  type: "multi"
  path_data: [
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_3particle_validation.nc'
    ]
  output_cols: ["x", "y", "z", "d"]
  maxnum_particles: 3
  shuffle: True
  labels: True
  null_weight: 0.0
  bins: 10
  
train_transforms:
  RandomVerticalFlip: True
  RandomHorizontalFlip: True
  Normalize: 'norm'
  ToTensor: True
  
validation_transforms:
  Normalize: 'norm'
  ToTensor: True

train_iterator:
  num_workers: 8
  batch_size: 24
  pin_memory: True
  shuffle: True
  
valid_iterator:
  num_workers: 8
  batch_size: 32
  pin_memory: True
  shuffle: False

vae:
  type: "att-vae"
  weights: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/vae/results/double_channel_1221/best.pt"
  image_channels: 1
  out_image_channels: 2
  hidden_dims: [50, 73, 96, 304, 906, 1820]
  z_dim: 1146
  weights: False
  
decoder:
  type: "gru-decoder"
  hidden_size: 1146
  output_size: 103
  n_layers: 3
  dropout: 0.20486082287158408
  bidirectional: True
  weights: False
  
regressor:
  type: "multi-head-dense"
  tasks: ["x", "y", "z", "d"]
  hidden_dims: [6308, 492, 492, 492]
  dropouts: [0.5, 0.3, 0.3, 0.3]
  weights: False

rnn_optimizer: 
  lr: 0.0005788796715932872
  weight_decay: 5.11295393332616e-06
  
particle_optimizer: 
  lr: 0.0012004345972945582
  weight_decay: 0.0

callbacks:
  MetricsLogger:
    path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/results/xy"
    reload: False
  EarlyStopping:
    decoder:
      patience: 5
      verbose: True
      path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/results/xy/checkpoint.pt"
      tag: "rnn"  
    regressor:
      patience: 3
      verbose: True
      path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/results/xy/checkpoint.pt"
      tag: "linear"
#   ExponentialLR:
#     decoder:
#       gamma: 0.95
#     regressor:
#       gamma: 0.95
  ReduceLROnPlateau: 
    decoder:
      mode: "min"
      factor: 0.2
      patience: 1
      min_lr: 1.0e-10
      verbose: True
    regressor:
      mode: "min"
      factor: 0.2
      patience: 1
      min_lr: 1.0e-08
      verbose: True

trainer:
  type: "decoder-vae"
  start_epoch: 0
  epochs: 100
  batches_per_epoch: 2724
  clip: 50.0
  alpha: 1.0
  beta: 1.0
  path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/results/xy"
  forcing: 0.7417336749305294
  label_smoothing: 0.11580195546948385
  focal_gamma: 1.1408107491208297