log: '/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/echo'

train_data:
  type: "nshot_kways"
  path_data: {
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_1particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_2particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_3particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_4particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_5particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_6particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_7particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_8particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_9particle_gamma_600x400_training.nc': 50000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_10particle_gamma_600x400_training.nc': 50000
    }
  output_cols: ["x", "y", "z", "d"]
  maxnum_particles: 13
  shuffle: True
  labels: True
  bins: [60, 40]
  binned_cols: ["x", "y"]
  n_shot: 2
  k_ways: 12
  
validation_data:
  type: "multi"
  path_data: {
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_1particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_2particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_3particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_4particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_5particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_6particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_7particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_8particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_9particle_gamma_600x400_validation.nc': 200,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_10particle_gamma_600x400_validation.nc': 200
    }
  output_cols: ["x", "y", "z", "d"]
  maxnum_particles: 13
  shuffle: True
  labels: True
  bins: [60, 40]
  binned_cols: ["x", "y"]
  
test_data:
  type: "multi"
  path_data: [
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_1particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_2particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_3particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_4particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_5particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_6particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_7particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_8particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_9particle_gamma_600x400_test.nc',
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_10particle_gamma_600x400_test.nc',
    ]
  output_cols: ["x", "y", "z", "d"]
  maxnum_particles: 13
  shuffle: True
  labels: True
  bins: [60, 40]
  binned_cols: ["x", "y"]
  
train_transforms:
  RandomVerticalFlip: True
  RandomHorizontalFlip: True
  Normalize: 'norm'
  ToTensor: True
  
validation_transforms:
  Normalize: 'norm'
  ToTensor: True
  
test_transforms:
  Normalize: 'norm'
  ToTensor: True

train_iterator:
  num_workers: 8
  batch_size: 1
  pin_memory: True
  shuffle: True
  
valid_iterator:
  num_workers: 8
  batch_size: 32
  pin_memory: True
  shuffle: False
  
test_iterator:
  num_workers: 8
  batch_size: 32
  pin_memory: True
  shuffle: False

vae:
  type: "att-vae"
  weights: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/vae/results/double_channel_0203/best.pt"
  image_channels: 1
  out_image_channels: 2
  hidden_dims: [114, 59, 34, 627, 544, 2000]
  z_dim: 1014
  
decoder:
  type: "gru-decoder"
  hidden_size: 1014
  output_size: 103
  n_layers: 3
  dropout: 0.20486082287158408
  bidirectional: True
  weights: False
  
regressor:
  type: "multi-head-dense"
  tasks: ["x", "y", "z", "d"]
  hidden_dims: [6308, 492, 492, 492]
  dropouts: [0.5, 0.3, 0.3, 0.3]
  weights: False

rnn_optimizer: 
  type: "lookahead-diffgrad"
  lr: 0.0005788796715932872
  weight_decay: 5.11295393332616e-06
  
particle_optimizer: 
  type: "lookahead-diffgrad"
  lr: 0.0012004345972945582
  weight_decay: 0.0

callbacks:
  MetricsLogger:
    path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/results/12_25"
    reload: False
  EarlyStopping:
    decoder:
      patience: 5
      verbose: True
      path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/results/12_25/checkpoint.pt"
      tag: "rnn"  
    regressor:
      patience: 3
      verbose: True
      path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/results/12_25/checkpoint.pt"
      tag: "linear"
#   ExponentialLR:
#     decoder:
#       gamma: 0.95
#     regressor:
#       gamma: 0.95
  ReduceLROnPlateau: 
    decoder:
      mode: "min"
      factor: 0.2
      patience: 2
      min_lr: 1.0e-08
      verbose: True
    regressor:
      mode: "min"
      factor: 0.2
      patience: 2
      min_lr: 1.0e-08
      verbose: True

trainer:
  type: "decoder-vae"
  regressor_loss: "xsigmoid"
  start_epoch: 0
  epochs: 100
  batches_per_epoch: 1000
  clip: 1.0
  max_grad_norm: 5.0
  alpha: 1.0
  beta: 1.0
  path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/decoder/echo"
  forcing: 0.7
  label_smoothing: 0.11580195546948385
  focal_gamma: 1.1408107491208297
  beam_size: 200