#!/bin/bash
### Job Name
#PBS -N pre_hist
### Project code
#PBS -A NEOL0007
#PBS -l walltime=12:00:00
#PBS -q regular
### Merge output and error files
#PBS -j oe
### Select 1 node with 36 CPUs
#PBS -l select=1:ncpus=36:mpiprocs=36
### Send email on abort, begin and end
###PBS -m abe
### Specify mail recipient
#PBS -M mhayman@ucar.edu

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

cd $HOME/Python/holodec-ml/scripts/mhayman/histogram_estimation/

module load python
ncar_pylib

### Run the executable
python run_preprocess_decimate_cheyenne.py
