#!/bin/bash -l
### Job Name
#SBATCH --job-name=hist
### Project code
#SBATCH --account=NEOL0007
#SBATCH --ntasks=1
###SBATCH --cpus-per-task=16
#SBATCH --time=04:00:00
#SBATCH --gres=gpu:v100:1
#SBATCH --output=hist.o.%j

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

cd $HOME/Python/holodec-ml/scripts/mhayman/ImageProcess

#module load python
module load cuda/10.1 ncarenv/1.3 gnu/7.4.0 ncarcompilers/0.5.0 python
source $HOME/.bashrc
source activate ml-casper


#module load ncarenv/1.3 gnu/7.4.0 ncarcompilers/0.5.0 python/3.7.5 cuda/10.0
#ncar_pylib ncar_20191211 
#pip install -e .

### Run the executable
python run_train_1d_psd_casper.py
