#!/bin/bash -l
### Job Name
#PBS -N hypvae
### Project code
#PBS -A NEOL0007
#PBS -l walltime=12:00:00
#PBS -q casper
### Merge output and error files
###PBS -j oe
###PBS -k eod
#PBS -o hypvaeSA.o
#PBS -e hypvaeSA.e
### Select 1 node with 36 CPUs
#PBS -l select=1:ngpus=1 -l gpu_type=v100
### Send email on abort, begin and end
###PBS -m abe
### Specify mail recipient
#PBS -M mhayman@ucar.edu

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

cd $HOME/Python/holodec-ml/scripts/mhayman/hist_vae

#module load python
module load cuda/10.1 ncarenv/1.3 gnu/7.4.0 ncarcompilers/0.5.0 python
source $HOME/.bashrc
source activate ml-casper


#module load ncarenv/1.3 gnu/7.4.0 ncarcompilers/0.5.0 python/3.7.5 cuda/10.0
#ncar_pylib ncar_20191211 
#pip install -e .

### Run the executable
python run_opt_hyp_histvae_sa_d.py
