#!/bin/bash -l
### Job Name
#PBS -N hypvae2d
### Project code
#PBS -A NEOL0007
#PBS -l walltime=12:00:00
#PBS -q casper
### Merge output and error files
###PBS -j oe
###PBS -k eod
#PBS -o hypvae2d.o
#PBS -e hypvae2d.e
### Select 1 node with 36 CPUs
#PBS -l select=1:ngpus=1:mem=10GB -l gpu_type=v100
### PBS -l #PBS -l select=1:ncpus=8:ngpus=1:mem=10GB:vnode=^casper36
### Send email on abort, begin and end
###PBS -m abe
### Specify mail recipient
#PBS -M mhayman@ucar.edu


export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

cd $HOME/Python/holodec-ml/scripts/mhayman/hist_vae

#module load python
module load cuda/10.1 ncarenv/1.3 gnu/7.4.0 ncarcompilers/0.5.0 python
source $HOME/.bashrc
source activate ml-casper

### Run the executable
python run_opt_hyp_histvae_2D.py
