#!/bin/bash -l
### Job Name
#SBATCH --job-name=train_unet
### Project code
#SBATCH --account=NEOL0007
#SBATCH --ntasks=1
###SBATCH --cpus-per-task=16
#SBATCH --time=01:00:00
#SBATCH --constraint=gpu
#SBATCH --train_unet.out.%j

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

cd $HOME/Python/holodec-ml/scripts/mhayman/ImageProcess

module load python
ncar_pylib

### Run the executable
python RandomImage_UNet_ConvT_FullScript.py
