log: 'test'
type: "encoder-vae"

data:
  path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
  num_particles: "50-100"
  maxnum_particles: 100
  output_cols: ["x", "y", "z", "d", "binary"]
  subset: False
  
transforms:
  #RandomVerticalFlip: False
  #RandomHorizontalFlip: False
  Rescale: 600
  Normalize: 'norm'
  ToTensor: True

iterator:
  num_workers: 16
  batch_size: 32
  pin_memory: True
  shuffle: True

model:
  image_channels: 1
  hidden_dims: [3, 94, 141, 471, 425, 1122]
  z_dim: 1277
  dense_hidden_dims: [100]
  dense_dropouts: [0.0]
  tasks: ["x", "y", "z", "d", "binary"]
  pretrained_model: "test/pretrained.pt"

optimizer: 
  type: "lookahead-diffgrad"
  lr: 0.00001

callbacks:
  MetricsLogger:
    path_save: "test"
    reload: False
  EarlyStopping:
    patience: 5
    verbose: True
    path_save: "test/checkpoint.pt"
  ExponentialLR:
    gamma: 0.99
    
#   ReduceLROnPlateau: 
#     mode: "min"
#     factor: 0.2
#     patience: 2
#     min_lr: 0.00000001
#     verbose: True

trainer:
  start_epoch: 0
  epochs: 1
  clip: 1.0
  alpha: 1.0
  beta: 1.0
  path_save: "test"
  test_image: "test/image_600.pkl"
  