path_data: "/Users/ggantos/PycharmProjects/holodec-ml/data/"
path_save: "/Users/ggantos/PycharmProjects/aiml-utils/aimlutils/hyper_opt/"
model_name: "attn"
num_particles: "large"
random_seed: 328942
output_cols: ["x", "y", "z", "d", "hid"]
scaler_out: "MinMaxScaler"
num_z_bins: False
subset: 0.1
mass: False
metric: "mae"
noisy_sd: 0.1
attention_network:
  activation: "relu"
  output_num: 5
train:
  epochs: 40
  batch_size: 64
  verbose: 1