path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/holodec/testing/attention/"
model_name: "attn"
num_particles: "large"
random_seed: 328942
output_cols: ["x", "y", "z", "d", "hid"]
scaler_out: "MinMaxScaler"
num_z_bins: False
subset: 0.1
mass: False
metric: "mae"
noisy_sd: 0.1
attention_network:
  attention_neurons: 100
  hidden_layers: 2
  hidden_neurons: 100
  activation: "relu"
  min_filters: 16
  output_num: 5 
train:
  learning_rate: 0.001
  epochs: 20
  batch_size: 64
  verbose: 1
