path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/ggantos/holodec/optuna/test/"
model_name: "attn"
num_particles: "large"
random_seed: 328942
output_cols: ["x", "y", "z", "d", "hid"]
scaler_out: "MinMaxScaler"
num_z_bins: False
subset: 0.1
mass: False
metric: "mae"
noisy_sd: 0.1
attention_network:
  activation: "relu"
  output_num: 5
train:
  epochs: 100
  batch_size: 64
  verbose: 1
callbacks:
  EarlyStopping:
    monitor: "val_loss"
    patience: 3
  ReduceLROnPlateau:
    monitor: "val_loss"
    factor: 0.2
    patience: 1
    min_lr: 0.0000001
    mode: "auto"
  CSVLogger:
    filename: "/glade/p/cisl/aiml/ggantos/holodec/optuna/test/training.txt"
    separator: " "
    append: True