path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/ggantos/holodec/attn/base"
model_name: "attn"
num_particles: "large"
random_seed: 328942
output_cols: ["x", "y", "z", "d", "hid"]
scaler_out: "MinMaxScaler"
subset: 0.25
num_z_bins: False
mass: False
metric: "mae"
noisy_sd: 0.2
attn_network:
  optimizer: "adam"
  batch_size: 256
  epochs: 2
  verbose: 1
  
  attention_neurons: 100
  hidden_layers: 1
  hidden_neurons: 100
  activation: "relu"
  min_filters: 4
  filter_width: 5
  pooling: "mean"
  pooling_width: 2
  filter_growth_rate: 2
  output_num: 2