log:
  save_path: "test/log.txt"

slurm:
  jobs: 1
  batch:
    account: "NAML0001"
    gres: "gpu:v100:1"
    mem: "256G"
    n: 8
    t: "12:00:00"
    J: "hyper_opt"
    o: "hyper_opt.out"
    e: "hyper_opt.err"

optuna:
  name: "holodec_optimization.db"
  reload: 0
  objective: "/Users/ggantos/PycharmProjects/holodec-ml/scripts/ggantos/objective.py"
  direction: "minimize"
  metric: "val_loss"
  n_trials: 2
  gpu: False
  save_path: '/Users/ggantos/PycharmProjects/aiml-utils/aimlutils/hyper_opt/'
  sampler:
    type: "TPESampler"
  parameters:
    attention_neurons:
      type: "int"
      settings:
          name: "attention_neurons"
          low: 50
          high: 150
    hidden_layers:
      type: "int"
      settings:
        name: "hidden_layers"
        low: 1
        high: 4
    hidden_neurons:
      type: "int"
      settings:
        name: "hidden_neurons"
        low: 50
        high: 150
    min_filters:
      type: "int"
      settings:
        name: "min_filters"
        low: 8
        high: 24
    learning_rate:
      type: "float"
      settings:
        name: "learning_rate"
        low: 0.00001
        high: 0.01