path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/ggantos/holodec/unet/jnet_5/"
num_particles: "medium"
output_cols: ["x", "y", "hid"]
scaler_out: "MinMaxScaler"
bin_factor: 5
subset: 0.10
mass: False
h: 0

