path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/ggantos/holodec/unet/jnet_10_1to25/"
model_name: "unet"
num_particles: [1,2,3,4,5,6,7,8,9,10,"12-25"]
random_seed: 328942
output_cols: ["x", "y", "hid"]
scaler_out: "MinMaxScaler"
bin_factor: 10
subset: [500,500,500,500,500,500,500,500,500,500,6500]
input_col: "image"
mass: False
loss: "unet_loss_xy"
unet:
  use_batch_norm: True
  num_classes: 1
  filters: 64
  dropout: 0.2
  output_activation: 'sigmoid'
  use_attention: True
  pool_down: [2,2,2,5]
  pool_up: [2,2]
  skip_pool: 10
train:
  learning_rate: 0.001
  epochs: 10
  batch_size: 8
  verbose: 2