seed: 1000
save_loc: "/glade/work/schreck/repos/HOLO/style/holodec-ml/results/weights/0"

data:
    n_bins: 1000
    data_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_training.nc"
    raw_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_200000-210000.nc"
    tile_size: 512
    step_size: 128
    marker_size: 10
    total_positive: 6
    total_negative: 6
    total_training: 100000
    transform_mode: 'None'
    prefix: "random"
    output_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/style_transfered/0"
    use_cached: True
    device: "cpu"
    cores: 0
    
style:
    weights:
        alpha: 1.0
        beta: 1.0e09
        selection: 0
    raw:
        path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_200000-210000.nc"
        tiles_per_reconstruction: 5
        reconstruction_per_hologram: 35
        save_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/tiled_real"
        sampler: "random"
    synthetic: 
        save_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/tiled_synthetic"
        sampler: "random"
    generated:
        save_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/style_transfered/0"

transforms:
    training:
        RandomVerticalFlip:
            rate: 0.5
        RandomHorizontalFlip: 
            rate: 0.5
        Normalize:
            mode: 'sym'
#         GaussianBlur:
#             rate: 1.0
#             kernel_size: 1
#             sigma: 2.1252219359742823
#         GaussianNoise:
#             rate: 1.0
#             noise: 0.3258530643453389
#         AdjustBrightness:
#             rate: 1.0
#             brightness_factor: 1.269735791766263
        ToTensor: True
    validation:
        Normalize:
            mode: 'sym'
        ToTensor: True
    inference:
        Normalize:
            mode: 'sym'
            
model:
    name: "linknet"
    encoder_name: "vgg11"
    encoder_weights: "imagenet"
    in_channels: 1
    classes: 1
    activation: "sigmoid"
    
optimizer:
    learning_rate: 0.00014105651059948075
    weight_decay: 6.043702479460191e-06
    
trainer:
    epochs: 100
    train_batch_size: 16
    valid_batch_size: 16
    batches_per_epoch: 250
    valid_batches_per_epoch: 100
    stopping_patience: 4
    training_loss: "focal-tyversky"
    validation_loss: "dice"
    
inference:
    mode: "mask"
    batch_size: 32
    n_nodes: 1
    gpus_per_node: 1
    threads_per_gpu: 1
    save_metrics: False
    save_arrays: False
    save_probs: False
    probability_threshold: 0.5
    distance_threshold: 1.0e-03
    verbose: False
    data_set:
        path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_test.nc"
        name: "synthetic"
#         path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_200000-210000.nc"
#         name: "real"
        holograms:
            min: 0
            max: 10