path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/ggantos/holodec/unet/xy_base/"
model_name: "unet"
num_particles: "medium"
random_seed: 328942
output_cols: ["x", "y", "hid"]
scaler_out: "MinMaxScaler"
bin_factor: False
subset: 0.10
mass: False
loss: "unet_loss_xy"
unet:
  use_batch_norm: True
  num_classes: 1
  filters: 64
  dropout: 0.2
  output_activation: 'sigmoid'
  use_attention: True
train:
  learning_rate: 0.001
  epochs: 10
  batch_size: 8
  verbose: 1
