seed: 1000
save_loc: "/glade/work/schreck/repos/HOLO/clean/holodec-ml/results/echo"

data:
    n_bins: 1000
    data_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_training.nc"
    raw_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_203600-203700.nc"
    tile_size: 512
    step_size: 128
    marker_size: 10
    total_positive: 2
    total_negative: 2
    total_training: 50000
    output_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/tiled_synthetic/"
    device: "cpu"
    cores: 18

transforms:
    training:
        RandomVerticalFlip:
            rate: 0.5
        RandomHorizontalFlip: 
            rate: 0.5
        Normalize:
            mode: '255'
        GaussianBlur:
            rate: 1.0
            kernel_size: 1
            sigma: 3
        GaussianNoise:
            rate: 1.0
            noise: 0.1
        AdjustBrightness:
            rate: 1.0
            brightness_factor: 2.0
        ToTensor: True
    validation:
        Normalize:
            mode: '255'
        ToTensor: True
    inference:
        Normalize:
            mode: '255'
    
model:
    name: "R18-U-Net-No-Noise-No-Phase"
    color_dim: 1
    mode: "mask"
    
optimizer:
    learning_rate: 1.0e-04
    weight_decay: 0.0
    
trainer:
    epochs: 100
    train_batch_size: 16
    valid_batch_size: 16
    batches_per_epoch: 500
    stopping_patience: 5
    training_loss: "dice-bce"
    validation_loss: "dice"
    
inference:
    batch_size: 16
    n_nodes: 4
    gpus_per_node: 1
    threads_per_gpu: 2
    save_arrays: True
    save_probs: False
    probability_threshold: 0.5
    plot: False
    verbose: False
    data_set:
        path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_test.nc"
        name: "synthetic"
#         path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_200000-210000.nc"
#         name: "real"
        holograms:
            min: 0
            max: 10