data:
    n_bins: 1000
    data_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_training.nc"
    raw_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_203600-203700.nc"
    tile_size: 512
    step_size: 128
    marker_size: 10
    total_positive: 5
    total_negative: 5
    total_training: 50000
    output_path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/tiled_synthetic/"
    cores: 16
    
transforms:
    training:
        RandomVerticalFlip: 
            rate: 0.0
        RandomHorizontalFlip: 
            rate: 0.0
        Normalize:
            mode: '255'
        GaussianBlur:
            rate: 0.0
            kernel_size: 1
            sigma: 3
        GaussianNoise:
            rate: 0.0
            noise: 0.1
        AdjustBrightness:
            rate: 0.0
            brightness_factor: 2.0
        ToTensor: True
    validation:
        Normalize:
            mode: '255'
        ToTensor: True
    inference:
        Normalize:
            mode: '255'
    
model:
    name: "Resnet-18-U-Net"
    color_dim: 2
    mode: "mask"
    
optimizer:
    learning_rate: 1.0e-04
    weight_decay: 0.0
    
trainer:
    epochs: 200
    train_batch_size: 8
    valid_batch_size: 32
    batches_per_epoch: 200
    stopping_patience: 5
    output_path: "/glade/work/schreck/repos/HOLO/clean/holodec-ml/results/unet_baseline"
    
inference:
    batch_size: 6
    n_nodes: 1
    gpus_per_node: 1
    threads_per_gpu: 4
    save_arrays: True
    save_probs: False
    plot: False
    verbose: True
    data_set: 
        #path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_500particle_gamma_4872x3248_test.nc"
        #name: "synthetic"
        path: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/real_holograms_CSET_RF07_20150719_200000-210000.nc"
        name: "./"
        holograms: [10]