path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/ggantos/holodec/testing/xyzd_1/"
model_name: "cnn"
num_particles: 1
random_seed: 328942
output_cols: ["x", "y", "z", "d", "hid"]
scaler_out: "MinMaxScaler"
num_z_bins: False
subset: 0.25
mass: False
metric: "mae"
conv2d_network:
  filters: [8, 16, 32]
  kernel_sizes: [5, 5, 5]
  conv2d_activation: "relu"
  pool_sizes: [4, 4, 4]
  dense_sizes: [64, 32]
  dense_activation: "relu"
  lr: 0.001
  optimizer: "adam"
  loss: "mae"
  batch_size: 256
  metrics: ["TP","FP","TN","FN"]
  epochs: 2
  verbose: 1
