path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/ggantos/holodec/jnet/zd/1to25_10_new/"
model_name: "cnn"
num_particles: [1,2,3,4,5,6,7,8,9,10,"12-25"]
random_seed: 328942
output_cols: ["x", "y", "z", "d", "hid"]
scaler_out: "MinMaxScaler"
num_z_bins: False
subset: [500,500,500,500,500,500,500,500,500,500,6500]
mass: False
rad: 64
scale_image: False
FFT: False
metric: "mae"
conv2d_network:
  filters: [8, 16, 32]
  kernel_sizes: [5, 5, 5]
  conv2d_activation: "relu"
  pool_sizes: [4, 4, 4]
  dense_sizes: [64, 32]
  dense_activation: "relu"
  lr: 0.001
  optimizer: "adam"
  loss: "mae"
  batch_size: 256
  metrics: ["TP","FP","TN","FN"]
  epochs: 10
  verbose: 1
