path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/p/cisl/aiml/ggantos/holodec/testing/sherpa_multi/"
max_concurrent: 4
max_num_trials: 20
model_name: "cnn"
num_particles: "multi"
random_seed: 328942
output_cols: ["z","hid"]
scaler_out: "MinMaxScaler"
num_z_bins: 100
subset: 0.25
mass: False
metric: "mae"
kernel_size: 5
pool_size: 4
conv2d_network:
  lrs: [1e-5, 1e-4, 1e-3, 1e-2, 3e-5, 3e-4, 3e-3, 3e-2]
  conv_layers: [2,6]
  kernel_size: [3,7]
  pool_size: [2,6]
  filter_size: [2, 4, 8, 16, 32]
  dense_layers: [1, 5]
  dense_size_0: [8, 16, 32, 64]
  conv2d_activation: "relu"
  dense_activation: "elu"
  optimizer: "adam"
  loss: "categorical_crossentropy"
  batch_size: 256
  epochs: 2
  verbose: 1
  sherpa: True
  study: False
  trial: False
