path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "resnet"
model_name: "cnn"
num_particles: "multi"
random_seed: 328942
output_cols: ["x", "y", "z", "d"]
scaler_out: "StandardScaler"
num_z_bins: 100
subset: False
conv2d_network:
  filters: [8, 12, 16]
  kernel_sizes: [5, 5, 5]
  conv2d_activation: "leakyrelu"
  pool_sizes: [5, 5, 5]
  pool_dropout: 0.5
  dense_sizes: [64, 32]
  dense_dropout: 0.5
  dense_activation: "leakyrelu"
  output_activation: "linear"
  lr: 0.00025
  optimizer: "adam"
  loss: "mse"
  metrics: ["r2"]
  batch_size: 64
  epochs: 100
  verbose: 1
callbacks:
  ModelCheckpoint:
    monitor: "val_loss"
    filepath: "resnet/model.h5"
    save_best_only: True
    save_weights_only: True
  EarlyStopping:
    monitor: "val_loss"
    patience: 50
  ReduceLROnPlateau: 
    monitor: "val_loss"
    factor: 0.5
    patience: 1
    min_lr: 0.000000000000001
    mode: "auto"
  CSVLogger:
    filename: "resnet/training.txt"
    separator: " "
    append: False