path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
path_save: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/example_trainer"
model_name: "cnn"
num_particles: 3
random_seed: 328942
output_cols: ["x", "y", "z", "d"]
scaler_out: "MinMaxScaler"
num_z_bins: 100
subset: False
conv2d_network:
  filters: [8, 12, 16]
  kernel_sizes: [5, 5, 5]
  conv2d_activation: "relu"
  pool_sizes: [5, 5, 5]
  dense_sizes: [64, 32]
  dense_activation: "elu"
  lr: 0.001
  decay: 0.1
  optimizer: "adam"
  loss: "mse"
  metrics: ["mae"]
  batch_size: 256
  epochs: 1000
  verbose: 1
callbacks:
  ModelCheckpoint:
    monitor: "val_loss"
    filepath: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/example_trainer/model.h5"
    save_best_only: True
    save_weights_only: True
  EarlyStopping:
    monitor: "val_loss"
    patience: 50
  ReduceLROnPlateau: 
    monitor: "val_loss"
    factor: 0.2
    patience: 30
    min_lr: 0.0000001
    mode: "auto"
  CSVLogger:
    filename: "/glade/work/schreck/repos/holodec-ml/scripts/schreck/example_trainerh/training.txt"
    separator: " "
    append: True