log: 'best_att_2'

data:
  path_data: "/glade/p/cisl/aiml/ai4ess_hackathon/holodec/"
  num_particles: "multi"
  maxnum_particles: 100
  output_cols: ["x", "y", "z", "d"]
  subset: False
  
transforms:
  RandomVerticalFlip: True
  RandomHorizontalFlip: True
  Normalize: 'norm'
  ToTensor: True

iterator:
  num_workers: 24
  batch_size: 128
  pin_memory: True
  shuffle: True

model:
  image_channels: 1
  hidden_dims: [3, 94, 141, 471, 425, 1122]
  z_dim: 1277

optimizer: 
  type: "lookahead-diffgrad"
  lr: 0.0006426221935682487

callbacks:
  MetricsLogger:
    path_save: "best_att_2"
    reload: False
  EarlyStopping:
    patience: 100
    verbose: True
    path_save: "best_att_2/checkpoint.pt"
  ExponentialLR:
    gamma: 0.95
    
#   ReduceLROnPlateau: 
#     mode: "min"
#     factor: 0.5
#     patience: 5
#     min_lr: 0.000000000000001
#     verbose: True

trainer:
  start_epoch: 66
  epochs: 500
  clip: 1.0
  alpha: 1.0
  beta: 1.0
  kld_weight: []
  path_save: "best_att_2"
  test_image: "/glade/work/schreck/repos/holodec-ml/holodecml/vae/image_600.pkl"
  