log: '/glade/work/schreck/repos/HOLO/merge/holodec-ml/scripts/schreck/vae'

train_data:
  type: "multi"
  path_data: {
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_1particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_2particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_3particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_4particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_5particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_6particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_7particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_8particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_9particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_10particle_gamma_600x400_training.nc': 10000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_12-25particle_gamma_600x400_training.nc': 80000
    }
  output_cols: ["x", "y", "z", "d"]
  maxnum_particles: 100
  shuffle: True
  labels: False
  
validation_data:
  type: "multi"
  path_data: {
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_1particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_2particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_3particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_4particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_5particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_6particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_7particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_8particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_9particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_10particle_gamma_600x400_validation.nc': 1000,
    '/glade/p/cisl/aiml/ai4ess_hackathon/holodec/synthetic_holograms_12-25particle_gamma_600x400_validation.nc': 8000
    }
  output_cols: ["x", "y", "z", "d"]
  maxnum_particles: 10
  shuffle: False
  labels: False
  
train_transforms:
  RandomVerticalFlip: True
  RandomHorizontalFlip: True
  Normalize: 'norm'
  ToTensor: True
  
validation_transforms:
  Normalize: 'norm'
  ToTensor: True
  
test_transforms:
  Normalize: 'norm'
  ToTensor: True

train_iterator:
  num_workers: 8
  batch_size: 24
  pin_memory: True
  shuffle: True
  
valid_iterator:
  num_workers: 8
  batch_size: 32
  pin_memory: True
  shuffle: False
  
test_iterator:
  num_workers: 8
  batch_size: 32
  pin_memory: True
  shuffle: False
  
model:
  type: "att-vae"
  image_channels: 1
  out_image_channels: 2
  hidden_dims: [114, 59, 34, 627, 544, 2000]
  z_dim: 1014
  weights: False

optimizer:
  type: "adam"
  lr: 7.106865882189022e-05
  weight_decay: 0.03687923743396445

callbacks:
  MetricsLogger:
    path_save: "/glade/work/schreck/repos/HOLO/merge/holodec-ml/scripts/schreck/vae"
    reload: False
  EarlyStopping:
    patience: 3
    verbose: True
    path_save: "/glade/work/schreck/repos/HOLO/merge/holodec-ml/scripts/schreck/vae/checkpoint.pt"
#   ExponentialLR:
#     gamma: 0.99
    
  ReduceLROnPlateau: 
    mode: "min"
    factor: 0.2
    patience: 1
    min_lr: 0.000000000000001
    verbose: True

trainer:
  type: "vae"
  training_loss: "xtanh"
  start_epoch: 0
  epochs: 1000
  batches_per_epoch: 10
  clip: 2.0
  alpha: 1.0
  beta: 29.73333480107324
  path_save: "/glade/work/schreck/repos/HOLO/merge/holodec-ml/scripts/schreck/vae"